### ISSUE TITLE
hey from Kurtosis!

### ISSUE THREAD

**Issue by h4ck3rk3y** [justfarming/contracts#1]
I am creating an issue as I couldn't find a better way to reach out to you! I saw this - https://github.com/justfarming/contracts/commit/ca92d2097a0e28b366d63cfbfd7ed091dad775a5

I realize our documentation isn't great but we do support pinning versions like if you are running a remote package you can have @ the end like https://docs.kurtosis.com/run/

Similarly you can do the same thing for the import_module call like https://github.com/kurtosis-tech/eth2-package/commit/09b235a37f62c2fd6f99dd466a9918d7d468831d

Do

```py
eth_network_module = import_module(
    "github.com/kurtosis-tech/eth-network-package/main.star@2.0.0"
)
```

This will pin it to tag 2.0.0, but you can pin branches or commits as well!

I have created this https://github.com/kurtosis-tech/kurtosis/issues/1255 to track improvement

I am gyani on our discord and would love for you to say hi :)

**Comment by tomknig** [comment]
Hi Gyani, Thanks for taking the time investigating and for proposing a solution. I've implemented your proposal in #3 and am currently testing it locally.
